// Build:
//  1. data/questions.*.jsonl + data/sources.json -> data/bank.mjs (the server imports it) and dist/bank-<hash>.js (the page loads it)
//  2. src/index.html with shared/rules.mjs and src/app.js inlined -> dist/index.html + one hashed immutable script
import { readFile, writeFile, mkdir, rm, copyFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const read = (f) => readFile(f, 'utf8');
const hash = (s) => createHash('sha256').update(s).digest('hex').slice(0, 10);

// ---- bank ----
const en = (await read('data/questions.en.jsonl')).split('\n').filter(Boolean).map((l) => JSON.parse(l));
const tr = (await read('data/questions.tr.jsonl')).split('\n').filter(Boolean).map((l) => JSON.parse(l));
const sources = JSON.parse(await read('data/sources.json'));
const trIds = new Set(tr.map((q) => q.id));
for (const q of en) if (!trIds.has(q.id)) { console.error('Build stopped: no Turkish for', q.id); process.exit(1); }
for (const q of en) if (!sources[q.file]) { console.error('Build stopped: unknown source file', q.file); process.exit(1); }
const bank = { questions: en, tr, sources: Object.fromEntries(Object.entries(sources).map(([k, v]) => [k, { title: v.title, url: v.url, topic: v.topic }])) };
const bankJson = JSON.stringify(bank);
await writeFile('data/bank.mjs', `// generated by scripts/build.mjs from data/questions.*.jsonl, do not edit\nexport default ${bankJson};\n`);

// ---- page ----
const [page0, rules, app] = await Promise.all(['src/index.html', 'shared/rules.mjs', 'src/app.js'].map(read));
for (const ph of ['/*__RULES__*/', '/*__APP__*/']) if (!page0.includes(ph)) { console.error('Build stopped: placeholder missing', ph); process.exit(1); }
const rulesInline = rules.replace(/^export\s+(const|function|let)\s+/gm, '$1 ').replace(/^export\s*\{[^}]*\};?\s*$/gm, '');
const bankName = `bank-${hash(bankJson)}.js`;
const page = page0.replace('/*__RULES__*/', () => rulesInline).replace('/*__APP__*/', () => app).replace('__BANK_URL__', '/' + bankName);
await rm('dist', { recursive: true, force: true }); await mkdir('dist', { recursive: true });
const scripts = [...page.matchAll(/<script>([\s\S]*?)<\/script>/g)].map((m) => m[1]);
for (const code of scripts) { try { new Function(code); } catch (e) { console.error('Build stopped: a page script does not parse:', e.message); process.exit(1); } }
const js = scripts.join('\n;\n');
const name = `reactor-${hash(js)}.js`;
const shipped = page.replace(/<script>[\s\S]*?<\/script>\s*/g, '').replace('</body>', `<script src="/${name}" defer></script>\n</body>`);
await writeFile('dist/index.html', shipped);
await writeFile('dist/' + name, js);
await writeFile('dist/' + bankName, `window.RXBANK=${bankJson};`);
await copyFile('src/favicon.svg', 'dist/favicon.svg');
await copyFile('src/theme.js', 'dist/theme.js');
try { await copyFile('src/og.png', 'dist/og.png'); } catch {}
console.log(`built dist/index.html (${(shipped.length / 1024).toFixed(0)} KB) + ${name} (${(js.length / 1024).toFixed(0)} KB) + ${bankName} (${(bankJson.length / 1024).toFixed(0)} KB), ${en.length} questions`);
